# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFoqe7xqnoabGBvTmzbwBkzDokHJE3xR
"""

from sklearn.datasets import load_sample_images
import tensorflow as tf

images=load_sample_images()["images"]

images[0].shape

images=tf.keras.layers.CenterCrop(height=80,width=120)(images) #resimlerin boyutunu ayarlıyoruz
images=tf.keras.layers.Rescaling(scale=1/255)(images) #resmi normalize ediyoruz

images.shape #4 boyut var. ilki batch sayısı diğer ikisi boyutlarını ve son değer de renkli resimler olduğundan kanalları temsil ediyor

conv_layer=tf.keras.layers.Conv2D(filters=32,kernel_size=7) #32 filtre kullanılıcak her birinin boyutu 7'ye 7 olacak yani kernel size

fmaps=conv_layer(images)

fmaps.shape

conv_layer=tf.keras.layers.Conv2D(filters=32,kernel_size=7,padding="same") #32 filtre kullanılıcak her birinin boyutu 7'ye 7 olacak yani kernel size

fmaps=conv_layer(images)

fmaps.shape # padding ile köşelerden kaybetmediğimizden boyut aynı kaldı

max_pool=tf.keras.layers.MaxPool2D(pool_size=2)

output=max_pool(fmaps)

output.shape

